- ShipperOptions.json
- package.json
ordoro/ordoro#8048
ordoro/shipper-options@2d47b78014cbe9347284d2ff64d2946a7550fd38
___
ordoro/shipper-options@2b47ca712fde072532fff548726a3e8e8105c369
> 8048-OnTrac-off-the-rails => master

- ShipperOptions.json
- package.json
ordoro/ordoro#8143
ordoro/shipper-options@5f2e715cd34eed90bd981f6f1163f99913a62a7a
___
ordoro/shipper-options@e4803d9259604d3e6eb684f1ea50a8f5d1d23a4b
> 8143-Third-Wheel => master

- ShipperOptions.json
- package.json
ordoro/ordoro#8089
ordoro/shipper-options@1dc31ce6d2521a89581656328ecdce2c091748b1
___
ordoro/shipper-options@8262c0fa45511b5154d3e9f47fbe5c79414c8e77
> 8089-DHL-Filing-Type => master

- ShipperOptions.json
ordoro/shipper-options@86bab58f7ba8e5f1220a736fc520d1adcf7829d5
> 8204-new-newgistics-options => master

- ShipperOptions.json
- package.json
ordoro/ordoro#7515
ordoro/shipper-options@df449960f19f6e8e8e270f36c5d240b98c76d6f1
> 7515-Pitney-Merchant-Shipper-Options => master

- ShipperOptions.json
- package.json
ordoro/ordoro#8424
ordoro/shipper-options@65540ffd1b931ee5143fb380879841992b67b82f
___
ordoro/shipper-options@1814110ebf637fc0ed5ab38aa8106b209a7ee645
> 8424-Newgistics-Non-Delivery-Option-Shipper-Options => master

- Dockerfile
- ShipperOptions.json
- cloudbuild.yaml
ordoro/shipper-options@5c6fd19bcb775811d4ad7540c0451863f806a124
> Cloud-Build-Github-App => master

- ShipperOptions.json
ordoro/ordoro#8442
ordoro/shipper-options@2e9f2a4518a3c1aead632554056ff020c85d6552
> 8442-endicia-restricted-delivery => master

- ShipperOptions.json
ordoro/ordoro#5838
ordoro/shipper-options@839881e3c343c6efbb8e11f515ca58b76821bf8c
> 8538-One-Rate-Multiple-Types-Shipper-Options => master

- ShipperOptions.json
- package.json
ordoro/shipper-options@2aec66001ce675c0a169cc89337a97446524c611
___
ordoro/shipper-options@a1ac525a6651dd9dd826f7e0abafa02a8a57d6a4
> 8574-amazon-shipper-shipping-method => master

- ShipperOptions.json
- package.json
ordoro/ordoro#8574
ordoro/shipper-options@93da3a767772f0286f3525d80a72ac5d42b8045f
___
ordoro/shipper-options@9f2467cd4db50b2f9a1dd0b0a8a67973a300347a
> 8574-Amazon-Shipping-For-SFP => master

- ShipperOptions.json
- package.json
ordoro/shipper-options@4acfc2d1406b41315d83cc97f3ec37d1f96e9c59
> 8923-ups-moore-shapes => master

- ShipperOptions.json
ordoro/ordoro#9006
ordoro/shipper-options@f24165d77aa8ac4a9cf3aaf3968e06bfdc804e46
> 9006-Visible-Shipper-Options => master

- ShipperOptions.json
- package.json
- Just copied from pitney, don't know if they are right
ordoro/ordoro#9129
ordoro/shipper-options@c389838b691232729eaaf0e0ae2ee8270054f5dc
___
ordoro/shipper-options@4f7250ab767e30d2dc9b992d53435a4815dcd42d
> 9129-Add-Visible-USPS-Reason-for-Export => master

- ShipperOptions.json
- package.json
ordoro/ordoro#5632
ordoro/ordoro#9317
ordoro/shipper-options@107f2d60e746b5d685e828626c8ee78078445eb6
___
ordoro/shipper-options@0e79504eb936e9ea5ac3a422fe3b272388c5d201
___
ordoro/ordoro#5632
ordoro/ordoro#9317
ordoro/shipper-options@8b6ee507084f07f30646be220a86fdbc8bcc0460
___
ordoro/shipper-options@8693a865b06b7b87460eaf8d9a64676c199b9bf2
> 5632-9317-UPS-FedEx-Reasons-For-Export => master

- ShipperOptions.json
- package.json
ordoro/shipper-options@d6a7ad44fb2b8cb0c99e22273a354f195e661867
___
ordoro/shipper-options@165d83170fc20f3eee0e006ade5c981d06d75e32
> 9557-priority-cubic => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@6399b448c6706b60c28eed6fc6363eb3154cbfe9
___
ordoro/shipper-options@6fb741ca4a6b4ff0650c4b139cc89195e719c1c8
> 9976-moore-auspost-options => master

- package-lock.json
- package.json
af91b4b8dd618d1a33abf4c006c24df55af2444a 
---
> 4788-bump-the-version => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10135
ordoro/shipper-options@ae7b6b8c987b4b9bb7dfdb5e3679bde0531a4efd
___
ordoro/shipper-options@def1dea74090ec872d650b5cd1a3952e78ba06d3
> 10135-Amazon-Shipping-USPS-Customs => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10182
ordoro/shipper-options@a9f3247a7a2786091f73587f2fef7e929a5a6011
___
ordoro/shipper-options@f2f9adbc5b821291081b599d8d63418729e918b2
> 10182-Endicia-GlobalPost => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10249
ordoro/shipper-options@bed3f030cbf34c8f9602a56b384932163b5c552d
___
ordoro/shipper-options@ecf7b3553fccfd53dd97adfb848b66b3805097e7
> 10249-Newgistics-Dangerous-Goods => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10117
ordoro/shipper-options@c11b51520312c904d3330d347bcbb03f334ac353
___
ordoro/shipper-options@57a27f1a5292c07399d47006b3bb37cc51c15e2f
> 10117-Simple-Change-For-A-Simple-Rate => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#9605
ordoro/shipper-options@a056e8792ca2153deac4d354ad357e3f117fefe6
___
ordoro/shipper-options@14963e47ad3dce861449915183465dacca502925
___
ordoro/ordoro#9605
ordoro/shipper-options@aec2f61a350a3063a07dc58899246ddc0f39a579
___
ordoro/shipper-options@38681bc09c950fa8ed31f775aebb709306bbbade
> 9605-Sendle-Options => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10652
ordoro/shipper-options@2ad79d22ecbaa6a1a7cb5633a540f08f1370d51d
___
ordoro/shipper-options@3e8a4ff295c5cbd266ac854e7a263e890cad0d3c
> 10652-Moore-Sendle => master

- ShipperOptions.json
ordoro/ordoro#7554
ordoro/shipper-options@f7f30276842c6bc9b1614e0cf91119d2e4e2bacb
> 7554-DHL-Ecommerce-Options => master

- ShipperOptions.json
- Added `type` param to shipping methods for use in selection of local
rates
ordoro/ordoro#7554
ordoro/shipper-options@e4c93b4c31751ad50e87c1d1552912bfdb05b916
> 7554-DHL-Ecommerce-Return-Options => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#11389
ordoro/shipper-options@649d775bf781fd470d101c8a8f26a80627d10396
___
ordoro/shipper-options@fab7e35d081980dc3572bd09dad13ec588554825
> 11389-DHL-Service-Endorsements => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#11481
ordoro/shipper-options@b30aa3781bca2cd8a18cffa5d529f3be91a10b56
___
ordoro/shipper-options@ee804a263eedab7f0a49bfa298a0b5cae39597d8
> 11481-Moore-DHL-eCommerce-Shipper-Options => master

- ShipperOptions.json
- package-lock.json
- package.json
- UPS said so
ordoro/ordoro#11716
ordoro/shipper-options@6fc298e9945f20c2a85484397f907a0d71d1ae92
___
ordoro/shipper-options@1bc44f98fbfa1235df861eeb185f9e0501754c6c
> 11716-Innovative-Names => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#11847
ordoro/shipper-options@f5f8f306e9b257d38795c29837805a4e93c08069
___
ordoro/shipper-options@c9f8c5112289e74db910116ec560cf8d1a02ddbe
> 11847-PB-Standard => master

- ShipperOptions.json
- package-lock.json
- package.json
- Added better shipping methods
- Removed first mile options as they are covered by new shipping methods
ordoro/ordoro#11941
ordoro/shipper-options@b54c8a8b31af0d96d96be21cd8fe3cca0aaa3e3c
___
ordoro/shipper-options@83195a408f3701a311cbee8b0229196f8213a6dc
> 11941-Re-Sendle-Options => master

- ShipperOptions.json
- package-lock.json
- package.json
- This is what Sendle wants
ordoro/ordoro#11941
ordoro/shipper-options@ce2091f64aced444697dd80da2ad4b43cd5a98a8
___
ordoro/shipper-options@dbe2a17ac467179bb3177f9ca3fa86493f231dd9
> 11941-Drop-Off-For-Sure => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10184
ordoro/shipper-options@dd3ef2167f78a6c2cd6872578b263395c2ed3a67
___
ordoro/shipper-options@abb97365d18116a5c7cdb8199626e7558b1697eb
___
ordoro/shipper-options@44d8472a102a4048beb472eef65c12145e9fcb79
> 10184-CBDS => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10184
ordoro/shipper-options@f53fd2d89e68f7ff795f139be8921eae75f81c68
___
ordoro/shipper-options@e2efc5be08ac6f9dc173b2f7b73dab678e21f343
> 10184-Cleanup-Shipper-Options => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#12149
ordoro/shipper-options@fe2259b994eb837c91805c59d66446335bd73236
___
ordoro/shipper-options@1aca2b8851439213b90659520b2ddf4441e4b72a
> 12149-Regional-Losers => master

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#12162
ordoro/shipper-options@390f43b2c4f8827b7fc2212175e2a776b3e565f0
___
ordoro/shipper-options@6510cbc4116812461fb94c66595979d692deaea0
> 12162-Remove-Cubic => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#12218
ordoro/shipper-options@f44c2ff856648d88f2abfd67c0a7f66a365e7d98
> 12218-These-Too => main

- ShipperOptions.json
- For FCM for now
ordoro/ordoro#12169
ordoro/shipper-options@f1b98a5f9313d40abbebe79e1e082395d9afd872
> 12169-transaction-fee => main

- ShipperOptions.json
- I do not know if this is even an option for pb standard, but if they are removing parcel select
I am going to add it there
- Include for pitney and pitney_merchant
ordoro/ordoro#12492
ordoro/shipper-options@012187a434e25d3a85b8629ceeed0c31722e801a
> 12492-ground-advantage => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#7287
ordoro/shipper-options@817a5052b6d9afb6d4c4a0cd14d0e4f72a7f1f4b
___
ordoro/shipper-options@35195b2317f979e51cd197933fd07a1205efb645
___
ordoro/ordoro#7287
ordoro/shipper-options@25214eec04b3149427e3d36d35f4c0d10a72454c
___
ordoro/shipper-options@9a20a898957c022a45de3ecd62709996c3746026
> 7287-UPS-Hazmat-Options => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@b5860e744295483bd97a5d396af56e2867438df7
> 12169-another-fee => main

- ShipperOptions.json
ordoro/ordoro#12554
ordoro/shipper-options@610a58703f6b937747b4853ec9f915c4aea2ab10
> 12554-pb-nondelivery-options => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#12554
ordoro/shipper-options@9818e8422347c231ef688a8bbae4d308bc613aff
> 12554-redirect-for-merchant => main

- ShipperOptions.json
- package-lock.json
- package.json
- per changes for UGA: add new methods and remove first class and parcel select
ordoro/ordoro#12606
ordoro/shipper-options@f314138313505acfed388fb4e74b402bbe8e0675
> 12606-sendle-for-uga => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#12704
ordoro/shipper-options@fbbd49ec70196a1e99e18ec9c5a2d074918a0820
___
ordoro/shipper-options@9bddba86bc6cb9f5c3f1e19a7ea20eba44bb8795
> 12704-Grounded-Amazon-Methods => main

- ShipperOptions.json
- package-lock.json
- package.json
- Not sure how helpful this is, but we want to display the DAP name for DAP customers
ordoro/ordoro#12986
ordoro/shipper-options@d46cd1c29edd57fb2b36a1f61094fb758756cda7
> 12986-ups-use-discounted-rate-names => main

- ShipperOptions.json
ordoro/shipper-options@30bbf3db288bea88b07a32e7096e71713bf0daee
> 12954-dhl-remove-deprecated-option => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#11955
ordoro/shipper-options@af5ffd07d2c6bf70439a8e09e34925f538084016
___
ordoro/shipper-options@23fab5fb28b666af0209cf8f60ed8a866829f197
> 11955-Reason-For-Sendle => main

- ShipperOptions.json
- package-lock.json
- package.json
- Only for manual tracking
ordoro/ordoro#13142
ordoro/shipper-options@a95e6b3d58ac3d63ef6566951e414339e0a0ca5c
___
ordoro/shipper-options@36fe24976e62cd55d5afb08b3adbdc6f80212a96
> 13142-RL-Really => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13263
ordoro/shipper-options@4934498e9c129246436d8478da80dc8a9500e731
___
ordoro/shipper-options@d68e5765c328610ebcc2c5b1c7fcc036b47503da
> 13263-Sendle-Extras => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@007c04f914bdba2164197ba069c7677081aedd29
___
ordoro/shipper-options@d05f092e1dd040c349f1a0b253ff5b2f90cd9a43
> 12844-Fedex-fipe => main

- ShipperOptions.json
- package-lock.json
- package.json
- Added new hubs
- Added International Connect Plus service
ordoro/ordoro#12904
ordoro/ordoro#11675
ordoro/shipper-options@4a8dfd0a5f405ffd7eb62c87c1a2617aa5ebd470
___
ordoro/shipper-options@659aad96a094c55d8067fa250f1ce2c0fa348bcc
> 12904-11675-FedEx-Extras => main

- ShipperOptions.json
- package-lock.json
- package.json
- For FedEx
ordoro/ordoro#13354
ordoro/ordoro#13319
ordoro/shipper-options@71a088883a618b8df84b34275a60f0832ccee083
___
ordoro/shipper-options@842bf4dd58025d9d684db642025b23039058d542
> 13354-13319-More-Options-For-FedEx => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#10817
ordoro/shipper-options@71ba4b8e07cacd0b4288dadf67b499929143b3ed
___
ordoro/shipper-options@af304da6dd78826e0e6ea838d6e1b534b43d00b3
> 10817-Not-So-Smart-Change => main

- ShipperOptions.json
- This can be at the vendor or method level
- Method level overrides vendor
ordoro/ordoro#13469
ordoro/shipper-options@32967a318731faa9460424f155895d48d7ca819d
> 13469-insurance-max => main

- README.md
ordoro/shipper-options@a2fcf939accc99fd0b732529330a882358309eb0
> Better-Docs => main

- package-lock.json
- package.json
ordoro/shipper-options@cee44e863bd1c0e71c557b57229ebffa50caa04e
> 13469-bump-version => main

- ShipperOptions.json
- package-lock.json
- package.json
- Response to brand test inquiry for FedEx CSP
ordoro/ordoro#12844
ordoro/shipper-options@1b5172cfeb66cc5244f6785729b668223b6b5803
___
ordoro/shipper-options@d7275d40a2d7202d1380bf567b7c3a64a1935e58
> 12844-branded-service-types => main

- ShipperOptions.json
- package-lock.json
- package.json
- For some fedex ground economy services
ordoro/ordoro#13596
ordoro/shipper-options@8b8d0213b20c26b2f8f0be899a5479d708687c20
> 13596-fedex-ancillary-endorsement => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@41edd40b44cfc58dfcbafac14ddf5e5bba012c93
___
ordoro/shipper-options@aceffa928c489e6f80cdb4d90bbceb1e01bba5b1
> fedex-brand-updates => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@62f97cfb91475542132a209b30bdf870dedc96ec
> remove-unsupported-fedex-options => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@82b414ce4a54190fbe7f566f47201874cdce3cf3
___
ordoro/shipper-options@e5039e98b8c1dc3cf0e77dd95350dfbbf9468e3c
___
ordoro/shipper-options@f100415a00d689e5994675da4e40a8b4af00e189
> fedex-cases-and-changed-type => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@de819226f6d89f567f89c4ae3e9341d8af931039
> 13697-fedex-pickup-updates => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13600
ordoro/shipper-options@79aa95a443a0b0f446a71b214f80dfeb1b7f7668
___
ordoro/shipper-options@20c74c8cc4aa87ea3d44f114a06b7e67d257a06f
> 13600-Names => main

- ShipperOptions.json
- package-lock.json
- package.json
- missing delivery conf option
ordoro/ordoro#13941
ordoro/shipper-options@3b9fecd3ad3f9bacc3964731260af90744444a89
> 13941-no-pref => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13987
ordoro/shipper-options@cb18331fe5b1669afc7ee0e2c0ac1a825127499a
___
ordoro/shipper-options@3a048f5e8b12cf45b92c7224c60ed55d79796297
> 13987-FedEx-Pickup-Locations => main

- package-lock.json
- package.json
ordoro/shipper-options@24ab7fc3303eb1e77b7631ca16b6733564c9c16d
___
ordoro/shipper-options@3325dfa01465b9059fd4f36932deee50fffd64fe
> 13990-bump-it => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13990
ordoro/shipper-options@69982c69662ca17006600c3b32cf2ad70154d20b
___
ordoro/shipper-options@54385245ec78821eb86118e7292c98ebcff03524
> 13990-dimensions-and-confirmation => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13990
ordoro/shipper-options@c81bb97e9080ac095dc7e5ac1e1b8c50a1902e13
___
ordoro/ordoro#13990
ordoro/shipper-options@5e6f3c7d7e6fb68689d048fb8835babb58ea6bd8
> 13990-USPS-Ship-Nondelivery-Options => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@f9f32325df2167d9d885ed3748a334eba8c34d33
___
ordoro/shipper-options@5d42d2a04014cb37179c52da3a6ca0e325a931eb
___
ordoro/shipper-options@507c85bfdd991e8fe3b060358629041cda718fc5
> 13497-pb-hazmat => main

- ShipperOptions.json
- package-lock.json
- package.json
- Renames for UPS
- Added option for Amazon Buy
ordoro/ordoro#14061
ordoro/ordoro#14080
ordoro/shipper-options@324510dbd4a7a8cdaed32bccd5dcdd4debf9d604
___
ordoro/shipper-options@47a8c8088c621ca4543f379ec66e0670d74b1d1e
> 14061-14080-Sureless-Post => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#13497
ordoro/shipper-options@052433c5db84ff741143745b7be081b95ee4c1d1
___
ordoro/shipper-options@df316ded6c663181d184e5f953f0e3d77f6fdc97
> 13497-Pitney-Merchant-HazMat => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@4843fd343e6bd1d6da07cefa7e6a44e4cd8f5260
___
ordoro/shipper-options@186d37bf17a9242fb5b444c7254032530bf45da3
> 14151-b13a_filing_option => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@8bac2dd84d7da959045219ce5b6a8b02357096b8
___
ordoro/shipper-options@3211fa8107b8b6bf4fb68e79593b46f09e42661f
___
ordoro/shipper-options@3195f4ad856d4c9e139e4c3faa6041468606eccf
___
ordoro/shipper-options@74aa40b7f9add9247bb089844535a160e3a60ac8
> 13990-reason-for-export => main

- ShipperOptions.json
- package-lock.json
- package.json
- went through with missy and decided to chop these
ordoro/ordoro#14278
ordoro/shipper-options@d4fa088f95ebf01058a55d3b0d35c02ec96ee512
___
ordoro/shipper-options@b2a4fb8d785c5b69f23bf5a3be4921844e5bc22d
> 14278-remove-weird-not-packages => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#14282
ordoro/shipper-options@3edd09c9a242462cbd61e6972d9824241d5d6326
___
ordoro/shipper-options@cdbe3a54ed3a0790de72548642f903123d309941
> 14282-USPS-Ship-Cleanup => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#14283
ordoro/shipper-options@3b1cf3a2ebd698d3b8a1fca17601afb914327344
___
ordoro/shipper-options@63c11c50376d080bef216153439bd4d3ae2a65c0
> 14283-Processing-Categories => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/shipper-options@fd482b131f554fb2c7274fa01a9f3279a8b12a28
___
ordoro/shipper-options@4f48fd99f11d43b1287f32808fef070c35c2bb21
> usps-ship-international-services => main

- ShipperOptions.json
- package-lock.json
- package.json
- Not sure what to call them so let me know if this isn't OK
ordoro/ordoro#13990
ordoro/shipper-options@07a5812c574802d386e0992e993c58a28d1afabe
> 13990-tax-types => main

- ShipperOptions.json
ordoro/ordoro#14289
ordoro/shipper-options@a7a04b67a4d718e4be1589986eb2bf3997beacf5
> 14289-hazmat-type => main

- package-lock.json
- package.json
ordoro/shipper-options@50a6ed3f2dfe5ec1b0968662c6e3e8387ed07484
> 14289-patch-it => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#9648
ordoro/shipper-options@acb9467e430818d4355522d3b9d1b9d5848bd33d
___
ordoro/shipper-options@9083d97367591b0cd66fc842e0d24d7fc268f326
___
ordoro/shipper-options@0ef0721c2e1d668ab35ed1cecf6187a709b1d5cd
> 9648-fedex-360 => main

- Dockerfile-build-package
- ShipperOptions.json
- package-lock.json
- package.json
- this is a USPS shipper, so we can mimic endicia and pitney for the value and max
ordoro/ordoro#14464
ordoro/shipper-options@316248a60ecea5f5757e01abd026a00984053741
___
ordoro/shipper-options@4eca5f5456ed6832d08ce08faf46a735278e625d
___
ordoro/shipper-options@dbb19b76e1d392b9d08020f9f94bc8af03ee91de
> 14464-usps-ship-surance => main

- ShipperOptions.json
- package-lock.json
- package.json
ordoro/ordoro#14444
ordoro/shipper-options@e8ef0e4b771573e137c706f23cb370a80c6c68fa
___
ordoro/shipper-options@d82da52d7332f7330fb9529d620409cebbb3351a
___
ordoro/ordoro#14444
ordoro/shipper-options@2ca7ccd21442593bb165672b13f6b7378d41e747
> 14444-Extra-Shipping-Methods => main
