ShipperOptions.json, package.json
- This will be used for postage payment and duties payment
ordoro/ordoro#8134
ordoro/shipper-options@b4f8f872e62a464e312a1940a1ca2dd907cd0f90
___
ordoro/shipper-options@db9cca42cfbeb660bfc33cde8871426908073abc
=> 8143-DHL-Payors => master

ShipperOptions.json, package.json
ordoro/shipper-options@1d75e2e232e84acd69b31b3b8d4d9c8e0d937c85
___
ordoro/shipper-options@c15a5a1a80a38920b87662715d11ccfe3ac89715
___
ordoro/shipper-options@43bcd65ba9b14a48ddf32faebbfd85aed9d4158b
___
ordoro/shipper-options@129b179751bd81edd48134a2d43cc7651e5dd422
=> 8341-dhlecomm => master

ShipperOptions.json, package.json
- Remove them until they can tell us that they should work or they update their list to reflect USPS changes
ordoro/ordoro#9216
ordoro/shipper-options@8ab419005bc8b55aea922612319bbdf37d9ad535
=> 9216-remove-dead-visible-box-types => master

ShipperOptions.json, package.json
- Added generic shipping_method because we can't get real Australia Post
rates, `Priority` is not a real shipping method for the Aussies
ordoro/ordoro#5724
ordoro/shipper-options@304f0858ff663838f4a0b6d209d7deefe499b834
___
ordoro/shipper-options@9654fc013c3815b4b131bf86f4f0e3e3054ea5f3
=> 5724-Australia-Post => master

ShipperOptions.json, package.json
- I don't know how these got there and it wasn't important until we
needed to literally list out these options that I noticed it.
- Anyway... gone.
ordoro/ordoro#9309
ordoro/shipper-options@c94155ebae750280d1a8f47a42f8538539b3a24d
___
ordoro/shipper-options@ea6f8315665dda705a726c665d4e02ceab5d1bc9
=> 9309-Remove-Dup-Options => master

ShipperOptions.json
* We had old consts back from when we (thought) we implemented adult
signature required and adult signature restricted delivery -> update
those sunnuvaguns
* ordoro/ordoro#4788
1329648dae82fa30f4bac22ccc79bf080213f319 
---
=> 4788-adult-signature => master

ShipperOptions.json, package-lock.json, package.json
ordoro/shipper-options@ff7411b449b08a6abf51e3587269b3f0d213b335
___
- `no_rates` will allow us to display shipping methods that don't have
rates in the mix of shipping methods that do have rates.
- This allows us to continue to exclude the shipping methods that are
normally rated but are excluded for a given package for whatever reason
ordoro/ordoro#7554
ordoro/shipper-options@1db7a5706ec594c657bc1c6f28cf6ec9ee22730c
___
ordoro/shipper-options@1b55d217cbcc034ebbeb76c410d3c90624d9cc39
=> 7554-DHL-Ecommerce-Return-Options => master

ShipperOptions.json, package-lock.json, package.json
- UPS does not support this option anymore
- So neither do we
ordoro/ordoro#11748
ordoro/shipper-options@5d8ec51e72fb1d4bc424403704f716933370fbd7
___
ordoro/shipper-options@c5b6ddfa204cac93de2ef560024d626f7d7ed5ef
=> 11748-UPS-No-Delivery-Confirmation => master

ShipperOptions.json, package-lock.json, package.json
- We need to label them as `no_rates: true` to make it possible to
display the shipping methods with a rate. God that sounds stupid.
- This designation only means that these shipping methods can display
if no rate is provided for it. It will display as TBD.
- Previously, Newgistics only worked with local rates. Pappy is now
expecting to get rates for newgistics.
- Did I clear that up?
ordoro/ordoro#11798
ordoro/shipper-options@2922a6c42e3a98d5bd3f3f3871a1c8fef77bb8f8
___
ordoro/shipper-options@62a71b21cfbe30bd774b7a516b42a065b78747af
=> 11798-Newgistics-Rates => master

ShipperOptions.json
* Pitney now supports `Signature with Restricted Delivery` so add it
as an option in Ordoro
ordoro/ordoro#11811
ordoro/shipper-options@5fd9a98178072724f943ac23f194a44c568b43eb
=> 11811-pitney-sig-with-restricted-delivery => master

ShipperOptions.json, package-lock.json, package.json
* Pitney now supports Flat packages so add as an option in Ordoro
ordoro/ordoro#7890
ordoro/ordoro#11810
ordoro/shipper-options@74a3aba0035cda3654b51dd4f11394da2ebdcff5
=> 7890-pitney-flat-package => master

ShipperOptions.json, package-lock.json, package.json
- To be used by marketing rate calculator but hopefully we can start
using it in the backend and pappy
ordoro/ordoro#12218
ordoro/shipper-options@bc9d2b1eb4f9ff6218802cd4e4495e19d5bc57f7
=> 12218-Moore-Box-Shape-Info => main

ShipperOptions.json, package-lock.json, package.json
- Need to have box shapes that have fixed dimensions but variable
weight, so having a simple `flat_rate` prop is too simple
- So `flat_rate: true` becomes `weight: false` and `dim_count: 0`
- This uses the existing `dim_count` prop
- This establishes `weight: value` prop so if we want to hard code a
weight in the future, we can.
ordoro/ordoro#12218
ordoro/shipper-options@7d3ea342317125eee8e1bd78d2c9c283309770ad
___
ordoro/shipper-options@5880156a8c6f516aecf968874dc3fe9d7b3f8bef
=> 12218-Even-Moore-Box-Shape-Info => main

ShipperOptions.json
- This seemed like it might be better to have both options during transition
then remove newgistics in favor of the new naming. Let me know if not.
- Remove unused and unavailable options from pb standard based on updated
pitney service types
brought to light and remove UGA for ordoro/ordoro#12492
ordoro/shipper-options@d5ae1a2dd6906bf3725889bafc6e41bfee9fdc0c
=> 12492-duping-newgs => main

ShipperOptions.json
- I wasn't sure about the names for these, the descriptions are missing in UPS docs,
but the options are enumerated so I figured it could be helpful.
- We will need these to be selectable in the UI and they are required for ADR
regulation set, which defines ground only EU to EU shipments
- Here is a link about tunnel restrictions https://support.mapandguide.com/intranet/2023/en/Content/glossary/GLO_tbc.htm
- Transport Category from some random UPS document found online
A category that ranges from 0 to 4 in
the ADR regulation set which indicates
the amount of points assigned to a
dangerous goods package to be in
compliance with the fully regulated
vehicle load exemption (ADR 1.1.3.6).
ordoro/ordoro#12680
ordoro/shipper-options@4ced6e037578e1fc68b442edf4ec9101762fdeb4
=> 12680-ups-moar-hazmats => main

ShipperOptions.json, package-lock.json, package.json
- LGENV is what we should have displayed for FLAT
- FLAT works for FCM though
- NMLETTER is a new fun type with dimensional restrictions
ordoro/ordoro#11899
ordoro/shipper-options@447ae9b845c033d3db129eff12b5c375893c4fdd
=> 11899-pitney-intl => main

ShipperOptions.json, package-lock.json, package.json
- These go through the same code
- I don't know if the dims work for pitney_merchant or if they're important,
but these should be the same essentially
- There are also some differences in the confirmation list, but i'm just
getting the work for the issue at hand
ordoro/ordoro#12883
ordoro/shipper-options@29cc1544de334900698fa0fccaa0e13c225a0d03
=> 12883-pitney-merchant-is-pitney => main

ShipperOptions.json, package-lock.json, package.json
- These should be the same essentially, they use the same api
- For ACH migrations
ordoro/shipper-options@09df03e1f83a3031057ab624bbc6e0106868f567
=> pitney-parity => main

ShipperOptions.json, package-lock.json, package.json
- Update to include FedEx in overnight offerings per fedex
ordoro/ordoro#12844
ordoro/shipper-options@df1b84878de2a259e58da78f5a61f054106779d5
___
ordoro/shipper-options@224aec3952d1eccd80ef79058f83589be5c19329
=> 12844-fedex-overnight-extra-hours-and-display => main

ShipperOptions.json, package-lock.json, package.json
- Added it to both PB Standard and Newgistics sections because why not
ordoro/ordoro#13275
ordoro/shipper-options@2a12e03f510a5507df3f44b0e5dfb9734be16d08
___
ordoro/shipper-options@f59daea8cdff664fee0d0ddf7597a9d717d592db
=> 13275-PB-Standard-Reason-For-Export => main

ShipperOptions.json, package-lock.json, package.json
- from UPS docs
- reformatted a couple of tax ids for readability when i was looking at this
ordoro/ordoro#13081
ordoro/shipper-options@6b5ab3d50ad3c8ada608d117a9aacd91051f7547
___
ordoro/shipper-options@e8899ea8f440e0c9b6a3564f0460103687788a46
=> 13081-ups-tax-id-types => main

ShipperOptions.json, package-lock.json, package.json
- We cannot support this at this time, and we don't really know how it works
ordoro/ordoro#13595
ordoro/shipper-options@652f9ddf4835c6ae768a401980f5ba70f547f164
___
ordoro/shipper-options@ebf05d2a7a560cfbed6a69292a2120f713434c30
=> 13595-fedex-parcel-return-removal => main

ShipperOptions.json, package-lock.json, package.json
ordoro/shipper-options@7e2bbd838a08996b45141d875e3a8d6e54f88d9b
___
ordoro/shipper-options@8e44a532b451f2a2ef63f0b42ddafc25faeed681
___
ordoro/shipper-options@55c3a1afbc4f434d4c4b48bc793943aa52abd220
___
- i guess they already changed it from when we added it last month
ordoro/shipper-options@7c4d639ba8f953fdc3db4a59380d877bd4b23015
=> fedex-package-branding => main

ShipperOptions.json
- Put it at the shipper level if all the box types require it
- If not it can live on the package
ordoro/ordoro#13710
ordoro/shipper-options@d1378ce5c70b0cbd48076a2eaf661c4f762fe0bf
=> 13710-package-dims => main

ShipperOptions.json
- use fedex naming even though it says smartpost
ordoro/ordoro#13864
ordoro/shipper-options@341a3cfe534afa312d39e747653a725ff437734b
=> 13864-amazon-fedex-ground-economy-smart-post => main

ShipperOptions.json, package-lock.json, package.json
- One Rate can't use box option
- Also hide the "One Rate" box shapes that are duplicates of the
existing options, but only if using CSP
ordoro/ordoro#14013
ordoro/shipper-options@9e74fcd5d523ab4cacbebcc75d9de3098f882886
=> 14013-One-Rate-Options => main

.github/workflows/test_on_push.yml, Dockerfile-build-package, cloudbuild.yaml
- move test to github actions, we don't really use cloudbuild anymore
- ordoro/ordoro#13124
ordoro/shipper-options@3b31b257d84c2e261d285757fd0834d504c74d72
=> 13124-remove-gcr-refs => main

ShipperOptions.json, package-lock.json, package.json
- i don't know if we can delete these outright just yet if there are lingering labels that had mapped services
- RFC: should i just delete them, or is this good for use in other areas?
- namely, the api label_info does box shape conversions by just grabbing the top level shipper keys here and that doesn't seem necessary if the shipper is no longer viable
- related to ordoro/ordoro#13346
ordoro/shipper-options@cbb4cf458c979ca8cee7020fb4f75e7987ccbc5f
___
ordoro/shipper-options@354c2199fab897391b73fb03446ce007d9b0023d
=> rfc-deprecated-shippers => main

ShipperOptions.json, package-lock.json, package.json
- If we send dimensions for a box shape and those dimensions don't fit within a flat rate box then that box type is ignored
- Support doesn't like, they would like flat rates to always return if that's the box type selected regardless of the input dimensions
- So, send 0x0x0 for these box types
- I'm completely guessing which of these matter based on the word 'flat'
ordoro/ordoro#13990
ordoro/shipper-options@d7dda8c17bc93fdfbdd4d369c61cb36db48843af
=> 13990-dimensions-required => main

ShipperOptions.json
- Copied some shit from pitney for packages that are basically the same
- gives us more context
- LETTERS and FLATS are not specifically package types in the way that we're using rate indicators to parse rates, but they are special types that our customers want, so this can be managed in the shipper code for better parity
ordoro/ordoro#14287
ordoro/shipper-options@e5c9ebcc5835d9c02925485f9a608d9c852e68c0
=> 14287-letters-and-flats => main

ShipperOptions.json
- remove some duplicate-ish packages
- remove pricing indicators
- remove categorical types of packages to allow them to fall under parcel
- rename Single Piece to Parcel for ease of customer transition
- reorder based on groupings
- TODO: add softpack and deal with it downstream, this update removes any ability to use softpack directly
ordoro/ordoro#14278
ordoro/shipper-options@60de935b5543d01a17dcbd3481a4c5aa2c401fae
=> 14278-usps-packages-again => main
